# Variables
@baseUrl = http://localhost:3333

###

# Health check
GET {{baseUrl}}/health

###

# @name auth
POST {{baseUrl}}/auth
Content-Type: application/json

{
  "username": "admin",
  "password": "admin"
}

###

# Create Order
POST {{baseUrl}}/order
Content-Type: application/json
Authorization: Bearer {{auth.response.body.token}}

{
  "numeroPedido": "v10089015vdb-06",
  "valorTotal": 10000,
  "dataCriacao": "2023-07-19T12:24:11.5299601+00:00",
  "items": [
    {
      "idItem": "2434",
      "quantidadeItem": 1,
      "valorItem": 1000
    },
    {
      "idItem": "5678",
      "quantidadeItem": 2,
      "valorItem": 2000
    }
  ]
}

###

# Get Order
GET {{baseUrl}}/order/v10089015vdb-06
Authorization: Bearer {{auth.response.body.token}}

###

# List Orders
GET {{baseUrl}}/order/list?page=1&pageSize=2
Authorization: Bearer {{auth.response.body.token}}

###

# Update Order
PUT {{baseUrl}}/order/v10089015vdb-06
Content-Type: application/json
Authorization: Bearer {{auth.response.body.token}}

{
  "valorTotal": 20000,
  "dataCriacao": "2023-07-19T12:24:11.5299601+00:00",
  "items": [
    {
      "idItem": "2434",
      "quantidadeItem": 3,
      "valorItem": 5000
    }
  ]
}

###

# Delete Order
DELETE {{baseUrl}}/order/v10089015vdb-06
Authorization: Bearer {{auth.response.body.token}}